## Python for data analysis
June 23, 2026

Nicole

In [3]:
# import packages
import numpy as np
import pandas as pd

In [6]:
gapminder = pd.read_csv("./data/gapminder_data.csv")
gapminder

          country  year         pop continent  lifeExp   gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088  739.981106
...           ...   ...         ...       ...      ...         ...
1699     Zimbabwe  1987   9216418.0    Africa   62.351  706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377  693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487  469.709298

[1704 rows x 6 columns]

In [7]:
gapminder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   year       1704 non-null   int64
 2   pop        1704 non-null   float64
 3   continent  1704 non-null   object
 4   lifeExp    1704 non-null   float64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 80.0+ KB

In [8]:
type(gapminder)

pandas.core.frame.DataFrame

In [12]:
# look at the first or last ten rows
gapminder.head(10)
gapminder.tail(10)

       country  year         pop continent  lifeExp   gdpPercap
1694  Zimbabwe  1962   4277736.0    Africa   52.358  527.272182
1695  Zimbabwe  1967   4995432.0    Africa   53.995  569.795071
1696  Zimbabwe  1972   5861135.0    Africa   55.635  799.362176
1697  Zimbabwe  1977   6642107.0    Africa   57.674  685.587682
1698  Zimbabwe  1982   7636524.0    Africa   60.363  788.855041
1699  Zimbabwe  1987   9216418.0    Africa   62.351  706.157306
1700  Zimbabwe  1992  10704340.0    Africa   60.377  693.420786
1701  Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702  Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703  Zimbabwe  2007  12311143.0    Africa   43.487  469.709298

In [13]:
# describe the data statistics
gapminder.describe()

             year           pop      lifeExp      gdpPercap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900

In [15]:
# only want to look at one variable: aggregate life expectancy data
(
    gapminder
    .agg({'lifeExp': 'mean'})
)

lifeExp    59.474439
dtype: float64

In [19]:
# display the descriptives at a custom header
(
    gapminder
    .agg(mean_lifeExp = ('lifeExp', 'mean'))
)

                lifeExp
mean_lifeExp  59.474439

In [18]:
# See the quantiles at 0.05 and 0.95. 
(
    gapminder
    .agg({'lifeExp': lambda x: x.quantile([0.05, 0.95])})
)

      lifeExp
0.05  38.4924
0.95  77.4370

In [23]:
# narrow down our data with query
(
    gapminder
    .query("year == 2007") #R equivalent: dplyr::filter. Always use double quotes
    .agg({'lifeExp': 'mean'})
)

lifeExp    67.007423
dtype: float64

In [28]:
# These two blocks are identical, same as dplyr::filter
(
    gapminder
    .query("country == 'United States' and year > 2000") # put the string within single brackets
)

(
    gapminder
    .query("country == 'United States'")
    .query("year > 2000")
)

            country  year          pop continent  lifeExp    gdpPercap
1618  United States  2002  287675526.0  Americas   77.310  39097.09955
1619  United States  2007  301139947.0  Americas   78.242  42951.65309

In [34]:
(
    gapminder
    .query("country in ['United States', 'Canada']")
)

            country  year          pop continent  lifeExp    gdpPercap
240          Canada  1952   14785584.0  Americas   68.750  11367.16112
241          Canada  1957   17010154.0  Americas   69.960  12489.95006
242          Canada  1962   18985849.0  Americas   71.300  13462.48555
243          Canada  1967   20819767.0  Americas   72.130  16076.58803
244          Canada  1972   22284500.0  Americas   72.880  18970.57086
245          Canada  1977   23796400.0  Americas   74.210  22090.88306
246          Canada  1982   25201900.0  Americas   75.760  22898.79214
247          Canada  1987   26549700.0  Americas   76.860  26626.51503
248          Canada  1992   28523502.0  Americas   77.950  26342.88426
249          Canada  1997   30305843.0  Americas   78.610  28954.92589
250          Canada  2002   31902268.0  Americas   79.770  33328.96507
251          Canada  2007   33390141.0  Americas   80.653  36319.23501
1608  United States  1952  157553000.0  Americas   68.440  13990.48208
1609  United States  1957  171984000.0  Americas   69.490  14847.12712
1610  United States  1962  186538000.0  Americas   70.210  16173.14586
1611  United States  1967  198712000.0  Americas   70.760  19530.36557
1612  United States  1972  209896000.0  Americas   71.340  21806.03594
1613  United States  1977  220239000.0  Americas   73.380  24072.63213
1614  United States  1982  232187835.0  Americas   74.650  25009.55914
1615  United States  1987  242803533.0  Americas   75.020  29884.35041
1616  United States  1992  256894189.0  Americas   76.090  32003.93224
1617  United States  1997  272911760.0  Americas   76.810  35767.43303
1618  United States  2002  287675526.0  Americas   77.310  39097.09955
1619  United States  2007  301139947.0  Americas   78.242  42951.65309

In [71]:
country_list = ["United States", "Canada"]

In [72]:
(
    gapminder
    .query("country in @country_list")
)

            country  year          pop continent  lifeExp    gdpPercap
240          Canada  1952   14785584.0  Americas   68.750  11367.16112
241          Canada  1957   17010154.0  Americas   69.960  12489.95006
242          Canada  1962   18985849.0  Americas   71.300  13462.48555
243          Canada  1967   20819767.0  Americas   72.130  16076.58803
244          Canada  1972   22284500.0  Americas   72.880  18970.57086
245          Canada  1977   23796400.0  Americas   74.210  22090.88306
246          Canada  1982   25201900.0  Americas   75.760  22898.79214
247          Canada  1987   26549700.0  Americas   76.860  26626.51503
248          Canada  1992   28523502.0  Americas   77.950  26342.88426
249          Canada  1997   30305843.0  Americas   78.610  28954.92589
250          Canada  2002   31902268.0  Americas   79.770  33328.96507
251          Canada  2007   33390141.0  Americas   80.653  36319.23501
1608  United States  1952  157553000.0  Americas   68.440  13990.48208
1609  United States  1957  171984000.0  Americas   69.490  14847.12712
1610  United States  1962  186538000.0  Americas   70.210  16173.14586
1611  United States  1967  198712000.0  Americas   70.760  19530.36557
1612  United States  1972  209896000.0  Americas   71.340  21806.03594
1613  United States  1977  220239000.0  Americas   73.380  24072.63213
1614  United States  1982  232187835.0  Americas   74.650  25009.55914
1615  United States  1987  242803533.0  Americas   75.020  29884.35041
1616  United States  1992  256894189.0  Americas   76.090  32003.93224
1617  United States  1997  272911760.0  Americas   76.810  35767.43303
1618  United States  2002  287675526.0  Americas   77.310  39097.09955
1619  United States  2007  301139947.0  Americas   78.242  42951.65309

In [59]:
# define NOT in a list
(
    gapminder
    .query("year == 2007")
    .query("continent == 'Americas'")
    .query("country not in @country_list")
)

                  country  year          pop continent  lifeExp     gdpPercap
59              Argentina  2007   40301927.0  Americas   75.320  12779.379640
143               Bolivia  2007    9119152.0  Americas   65.554   3822.137084
179                Brazil  2007  190010647.0  Americas   72.390   9065.800825
287                 Chile  2007   16284741.0  Americas   78.553  13171.638850
311              Colombia  2007   44227550.0  Americas   72.889   7006.580419
359            Costa Rica  2007    4133884.0  Americas   78.782   9645.061420
395                  Cuba  2007   11416987.0  Americas   78.273   8948.102923
443    Dominican Republic  2007    9319622.0  Americas   72.235   6025.374752
455               Ecuador  2007   13755680.0  Americas   74.994   6873.262326
479           El Salvador  2007    6939688.0  Americas   71.878   5728.353514
611             Guatemala  2007   12572928.0  Americas   70.259   5186.050003
647                 Haiti  2007    8502814.0  Americas   60.916   1201.637154
659              Honduras  2007    7483763.0  Americas   70.198   3548.330846
791               Jamaica  2007    2780132.0  Americas   72.567   7320.880262
995                Mexico  2007  108700891.0  Americas   76.195  11977.574960
1115            Nicaragua  2007    5675356.0  Americas   72.899   2749.320965
1187               Panama  2007    3242173.0  Americas   75.537   9809.185636
1199             Paraguay  2007    6667147.0  Americas   71.752   4172.838464
1211                 Peru  2007   28674757.0  Americas   71.421   7408.905561
1259          Puerto Rico  2007    3942491.0  Americas   78.746  19328.709010
1559  Trinidad and Tobago  2007    1056608.0  Americas   69.819  18008.509240
1631              Uruguay  2007    3447496.0  Americas   76.384  10611.462990
1643            Venezuela  2007   26084662.0  Americas   73.747  11415.805690

In [56]:
# Groupby function: R equivalent: dplyr::group_by
(
    gapminder
    .groupby('year')
    .agg({'lifeExp' : ['mean', 'min', 'max']})
)

        lifeExp
           mean     min     max
year
1952  49.057620  28.801  72.670
1957  51.507401  30.332  73.470
1962  53.609249  31.997  73.680
1967  55.678290  34.020  74.160
1972  57.647386  35.400  74.720
1977  59.570157  31.220  76.110
1982  61.533197  38.445  77.110
1987  63.212613  39.906  78.670
1992  64.160338  23.599  79.360
1997  65.014676  36.087  80.690
2002  65.694923  39.193  82.000
2007  67.007423  39.613  82.603

In [55]:
(
    gapminder
    .groupby('continent')
    .agg({'lifeExp' : ['mean', 'min', 'max']})
)

             lifeExp
                mean     min     max
continent
Africa     48.865330  23.599  76.442
Americas   64.658737  37.579  80.653
Asia       60.064903  28.801  82.603
Europe     71.903686  43.585  81.757
Oceania    74.326208  69.120  81.235

In [62]:
# Sorting the data in the order of lifeExp
(
    gapminder
    .query("year == 2007")
    .groupby('continent')
    .agg({'lifeExp': 'mean'})
    .sort_values('lifeExp', ascending = False)
)

             lifeExp
continent
Oceania    80.719500
Europe     77.648600
Americas   73.608120
Asia       70.728485
Africa     54.806038

In [67]:
# .Assign, R equivalent: dplyr::mutate
(
    gapminder
    .assign(gdp = lambda df: df['pop'] * df['gdpPercap'], 
           popInMillions = lambda df: df['pop'] / 1e6)
)

,country,year,pop,continent,lifeExp,gdpPercap,gdp,popInMillions
0,Afghanistan,1952,8425333.0,Asia,28.801,779.445314,6.567086e+09,8.425333
1,Afghanistan,1957,9240934.0,Asia,30.332,820.853030,7.585449e+09,9.240934
2,Afghanistan,1962,10267083.0,Asia,31.997,853.100710,8.758856e+09,10.267083
3,Afghanistan,1967,11537966.0,Asia,34.020,836.197138,9.648014e+09,11.537966
4,Afghanistan,1972,13079460.0,Asia,36.088,739.981106,9.678553e+09,13.079460
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418.0,Africa,62.351,706.157306,6.508241e+09,9.216418
1700,Zimbabwe,1992,10704340.0,Africa,60.377,693.420786,7.422612e+09,10.704340
1701,Zimbabwe,1997,11404948.0,Africa,46.809,792.449960,9.037851e+09,11.404948
1702,Zimbabwe,2002,11926563.0,Africa,39.989,672.038623,8.015111e+09,11.926563
1703,Zimbabwe,2007,12311143.0,Africa,43.487,469.709298,5.782658e+09,12.311143

In [70]:
# Trick: getting columns from the dataset
gapminder[['country', 'year', 'pop']]

          country  year         pop
0     Afghanistan  1952   8425333.0
1     Afghanistan  1957   9240934.0
2     Afghanistan  1962  10267083.0
3     Afghanistan  1967  11537966.0
4     Afghanistan  1972  13079460.0
...           ...   ...         ...
1699     Zimbabwe  1987   9216418.0
1700     Zimbabwe  1992  10704340.0
1701     Zimbabwe  1997  11404948.0
1702     Zimbabwe  2002  11926563.0
1703     Zimbabwe  2007  12311143.0

[1704 rows x 3 columns]

### Select and Drop Columns

In [80]:
# Selecting certain columns: Equivalent to dplyr::select
columns_wanted = ['country', 'year', 'pop']
(
    gapminder
    .filter(columns_wanted) 
)

          country  year         pop
0     Afghanistan  1952   8425333.0
1     Afghanistan  1957   9240934.0
2     Afghanistan  1962  10267083.0
3     Afghanistan  1967  11537966.0
4     Afghanistan  1972  13079460.0
...           ...   ...         ...
1699     Zimbabwe  1987   9216418.0
1700     Zimbabwe  1992  10704340.0
1701     Zimbabwe  1997  11404948.0
1702     Zimbabwe  2002  11926563.0
1703     Zimbabwe  2007  12311143.0

[1704 rows x 3 columns]

In [78]:
# Dropping columns
columns_notwanted = ['year', 'pop']
(
    gapminder
    .drop(columns = columns_notwanted)
)

          country continent  lifeExp   gdpPercap
0     Afghanistan      Asia   28.801  779.445314
1     Afghanistan      Asia   30.332  820.853030
2     Afghanistan      Asia   31.997  853.100710
3     Afghanistan      Asia   34.020  836.197138
4     Afghanistan      Asia   36.088  739.981106
...           ...       ...      ...         ...
1699     Zimbabwe    Africa   62.351  706.157306
1700     Zimbabwe    Africa   60.377  693.420786
1701     Zimbabwe    Africa   46.809  792.449960
1702     Zimbabwe    Africa   39.989  672.038623
1703     Zimbabwe    Africa   43.487  469.709298

[1704 rows x 4 columns]

In [81]:
# Selecting for columns that start with c
(
    gapminder
    .filter(regex = '^c')
)

          country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
1699     Zimbabwe    Africa
1700     Zimbabwe    Africa
1701     Zimbabwe    Africa
1702     Zimbabwe    Africa
1703     Zimbabwe    Africa

[1704 rows x 2 columns]

In [82]:
# Selecting for columns that end with p
(
    gapminder
    .filter(regex = 'p$')
)

             pop  lifeExp   gdpPercap
0      8425333.0   28.801  779.445314
1      9240934.0   30.332  820.853030
2     10267083.0   31.997  853.100710
3     11537966.0   34.020  836.197138
4     13079460.0   36.088  739.981106
...          ...      ...         ...
1699   9216418.0   62.351  706.157306
1700  10704340.0   60.377  693.420786
1701  11404948.0   46.809  792.449960
1702  11926563.0   39.989  672.038623
1703  12311143.0   43.487  469.709298

[1704 rows x 3 columns]

### Long to wide format

In [85]:
(
    gapminder
    .pivot(columns = 'year', # the columns need to be the thing that repeats across the observations
          index = ['country', 'continent'],
          values = 'lifeExp')
)

,year,1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007
country,continent,,,,,,,,,,,,
Afghanistan,Asia,28.801,30.332,31.997,34.020,36.088,38.438,39.854,40.822,41.674,41.763,42.129,43.828
Albania,Europe,55.230,59.280,64.820,66.220,67.690,68.930,70.420,72.000,71.581,72.950,75.651,76.423
Algeria,Africa,43.077,45.685,48.303,51.407,54.518,58.014,61.368,65.799,67.744,69.152,70.994,72.301
Angola,Africa,30.015,31.999,34.000,35.985,37.928,39.483,39.942,39.906,40.647,40.963,41.003,42.731
Argentina,Americas,62.485,64.399,65.142,65.634,67.065,68.481,69.942,70.774,71.868,73.275,74.340,75.320
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vietnam,Asia,40.412,42.887,45.363,47.838,50.254,55.764,58.816,62.820,67.662,70.672,73.017,74.249
West Bank and Gaza,Asia,43.160,45.671,48.127,51.631,56.532,60.765,64.406,67.046,69.718,71.096,72.370,73.422
Yemen Rep.,Asia,32.548,33.970,35.180,36.984,39.848,44.175,49.113,52.922,55.599,58.020,60.308,62.698
Zambia,Africa,42.038,44.077,46.023,47.768,50.107,51.386,51.821,50.821,46.100,40.238,39.193,42.384
Zimbabwe,Africa,48.451,50.469,52.358,53.995,55.635,57.674,60.363,62.351,60.377,46.809,39.989,43.487

In [90]:
(
    gapminder
    .pivot(columns = 'year',
          index = ['country', 'continent'],
          values = 'lifeExp')
    .reset_index()
    .melt(id_vars = ['country', 'continent'],
         value_name = 'lifeExpectacy')
)

                 country continent  year  lifeExpectacy
0            Afghanistan      Asia  1952         28.801
1                Albania    Europe  1952         55.230
2                Algeria    Africa  1952         43.077
3                 Angola    Africa  1952         30.015
4              Argentina  Americas  1952         62.485
...                  ...       ...   ...            ...
1699             Vietnam      Asia  2007         74.249
1700  West Bank and Gaza      Asia  2007         73.422
1701          Yemen Rep.      Asia  2007         62.698
1702              Zambia    Africa  2007         42.384
1703            Zimbabwe    Africa  2007         43.487

[1704 rows x 4 columns]

## Subset data for later use

- Read in 'gapminder_data.csv' data
- filter out year 2007 and continent Americas
- drop the year and continent columns
- save the new dataframe into a variable called gapminder_2007

In [91]:
# - Read in 'gapminder_data.csv' data
gapminder = pd.read_csv('./data/gapminder_data.csv')

In [93]:
# - filter out year 2007 and continent Americas
# - drop the year and continent columns
# - save the new dataframe into a variable called gapminder_2007
gapminder_2007 = (
    gapminder
    .query("year == 2007")
    .query("continent == 'Americas'")
    .drop(columns = ['year', 'continent'])
)

In [94]:
gapminder_2007

                  country          pop  lifeExp     gdpPercap
59              Argentina   40301927.0   75.320  12779.379640
143               Bolivia    9119152.0   65.554   3822.137084
179                Brazil  190010647.0   72.390   9065.800825
251                Canada   33390141.0   80.653  36319.235010
287                 Chile   16284741.0   78.553  13171.638850
311              Colombia   44227550.0   72.889   7006.580419
359            Costa Rica    4133884.0   78.782   9645.061420
395                  Cuba   11416987.0   78.273   8948.102923
443    Dominican Republic    9319622.0   72.235   6025.374752
455               Ecuador   13755680.0   74.994   6873.262326
479           El Salvador    6939688.0   71.878   5728.353514
611             Guatemala   12572928.0   70.259   5186.050003
647                 Haiti    8502814.0   60.916   1201.637154
659              Honduras    7483763.0   70.198   3548.330846
791               Jamaica    2780132.0   72.567   7320.880262
995                Mexico  108700891.0   76.195  11977.574960
1115            Nicaragua    5675356.0   72.899   2749.320965
1187               Panama    3242173.0   75.537   9809.185636
1199             Paraguay    6667147.0   71.752   4172.838464
1211                 Peru   28674757.0   71.421   7408.905561
1259          Puerto Rico    3942491.0   78.746  19328.709010
1559  Trinidad and Tobago    1056608.0   69.819  18008.509240
1619        United States  301139947.0   78.242  42951.653090
1631              Uruguay    3447496.0   76.384  10611.462990
1643            Venezuela   26084662.0   73.747  11415.805690